### ISSUE TITLE
Mettre le champs participant_type à null=False

### ISSUE THREAD

**Issue by Anna-Livia** [betagouv/CNR#140]
Je me demande si ça vaudrait pas le coup de mettre null à false...

_Originally posted by @dxb in https://github.com/betagouv/CNR/pull/130#discussion_r982388361_

**Comment by mjeammet** [comment]
@Anna-Livia est-ce qu'on est d'accord que cette Issue est obsolète ? De ce que j'ai compris de ce dont on a parlé ce matin, on veut pouvoir mettre None à ces champs si la personne ne veut pas s'investir localement.
