### ISSUE TITLE
Accessibilité

### ISSUE THREAD

**Issue by Anna-Livia** [betagouv/CNR#157]
dans les pages de question sur les thématiques, il faudrait utiliser des éléments <textarea> plutôt que des suites de champ <input> d'une seule ligne
le captcha est vraiment nécessaire ? je m'y suis repris à plusieurs fois pour le passer
Il manque un role="alert" sur les messages disant que les contributions ont bien été prises en compte ou que l'inscription s'est bien passée
La modale de boite à cookies n'est pas utilisable au clavier, elle est même masquée aux aides techniques. (pourquoi ne pas avoir utilisé le composant du DSFR ?)
les éléments <title> sont identiques sur toutes les pages, ils doivent être uniques

**Comment by dxb** [comment]
"dans les pages de question sur les thématiques, il faudrait utiliser des éléments <textarea> plutôt que des suites de champ d'une seule ligne" --> contraire à la recomandation de bluenov
