### ISSUE TITLE
Ajouter un lien vers les CGU avant de cocher sur l'index

### ISSUE THREAD

**Issue by mjeammet** [betagouv/CNR#185]

**Comment by BenoitSerrano** [comment]
@mjeammet je ne comprends pas cette issue :)

**Comment by mjeammet** [comment]
Déso c'était pas bien dit. J'ai cru comprendre que des gens voulaient accéder aux CGU depuis l'index et regrettaient qu'il y ait pas un lien au niveau de la checkbox. Je sais pas ce qu'il en est maintenant.
