### ISSUE TITLE
Comportement au clavier des accordéons de la page https://conseil-refondation.fr/inscription/

### ISSUE THREAD

**Issue by Flightan** [betagouv/CNR#200]
Lorsque l'on navigue au clavier sur les accordéons de la page https://conseil-refondation.fr/inscription/, en sélectionnant on ouvre l'accordéon, sans cocher la checkbox. Il devient alors difficile de rattraper et il faut souvent rafraichir la page et recommencer.

**Comment by benoitdequick** [comment]
Retirer la checkbox, reglerait le problème, non ?
