### ISSUE TITLE
La modale de boite à cookies n'est pas utilisable au clavier.

### ISSUE THREAD

**Issue by Flightan** [betagouv/CNR#204]
Elle est même masquée aux aides techniques. Est-ce facile de remplacer par le composant du systeme de design ?

**Comment by dxb** [comment]
https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/gestionnaire-de-consentement
Accessibilité
Le bandeau de consentement doit être le premier élément sélectionné lors de la navigation au clavier (avant les liens d’évitement) ou au lecteur d’écran. Il faut le placer en première position dans le DOM, juste après la balise <body> (et avant les liens d’évitement).
Gestion du focus : lorsque l’utilisateur confirme ses choix de cookies, repositionner l’utilisateur en haut de la page.
La fenêtre de finalité étant une modale, elle suit les mêmes recommandations que cette dernière. Il en est de même pour les boutons radios permettant de choisir l'état des finalité.
