### ISSUE TITLE
Parcours d'inscription

### ISSUE THREAD

**Issue by benoitdequick** [betagouv/CNR#212]
1. Lorsqu'on arrive sur la home, on donne son adresse électronique pour s'inscrire à une infolettre, on accepte les cgu et la ppd, on remplit le captcha. Je clique sur "Je participe".
https://conseil-refondation.fr/
- [ ] retirer le captcha
- [ ] retirer l'acceptation des cgu et ppd 
- [ ] revoir le wording du formulaire de la home avec un titre `<h2>Vous devez vous inscrire pour participer` et un `<label>Adresse électronique `

2. Sur https://conseil-refondation.fr/inscription/, l'adresse électronique est pré-remplie, mon prénom et mon cp sont obligatoires (mais je ne le sais pas encore), je coche les thématiques qui m'intéressent, je précise éventuellement dans quoi je veux m'impliquer localement, j'accepte **à nouveau** les cgu et ppd, je remplit **un nouveau** captcha et je "valide mon inscription".
- [ ] indiquer que tous les champs sont obligatoires
- [ ] retirer les checkboxes qui font doublons avec les accordéons (qui fonctionnent très bien)
- [ ] ajouter une case à cocher "Je souhaite recevoir la newsletter"

**Comment by BenoitSerrano** [comment]
On a découpé en plusieurs PRs, on s'en occupe ! :) Merci pour tes retours !
