### ISSUE TITLE
Regroupement des champs sur la page inscription

### ISSUE THREAD

**Issue by benoitdequick** [betagouv/CNR#224]
Plusieurs éléments `fieldset` sont utilisés et imbriqués sans élément `legend`.

Il est possible de simplifier de la sorte :

```
<fieldset>
<legend>
<h3>Pour améliorer notre école Exemple: participer à un débat dans l’établissement scolaire près de chez moi</h3>
</legend>
label + champ ville, département ou région 
  <fieldset>
      <legend>Je participe en tant que :</legend>
      boutons radios + radio button
 </fieldset>     
</fieldset> 
```

De plus, les éléments `fieldset` autour des éléments `input` adresse électronique, prénom, cp et checkbox cgu peuvent être retirés

**Comment by mjeammet** [comment]
TODO: investiguer la PR #234 pour voir si c'est pas déjà corrigé.

**Comment by mjeammet** [comment]
Bonjour @benoitdequick et merci pour l'audit et l'issue. On a décidé de simplifier au maximum pour ne garder que les fieldsets sur les checkboxes / radio buttons, en s'assurant qu'ils aient bien des légendes ! Hésite pas à commenter ou à fermer l'issue si ça te semble bon.
